#!/usr/bin/env bash
# prints to infinity and beyond indfinitely and I am invincible when a SIGTERM signal is received
msg()
{
	#prints a message when a SIGTERM signal is received
	echo "I am invincible!!!"
}
while [ 1 ]
do
	echo "To infinity and beyond"
	trap msg SIGTERM
	sleep 2
done
