#!/usr/bin/env bash
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
for NUM in {1..100}
do
	if ! (( $NUM % 15 ))
	then
		echo "FizzBuzz"
	elif ! (( $NUM % 3 ))
	then
		echo "Fizz"
	elif ! (( $NUM % 5 ))
	then
		echo "Buzz"
	else
		echo $NUM
	fi
done
