#!/usr/bin/env bash
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
n=1
while [ $n -le 20 ]
do
	echo $n
	if [ $n == 4 ]
	then
		echo "bad luck from China"
	elif [ $n == 9 ]
	then
		echo "bad luck from Japan"
	elif [ $n == 17 ]
	then
		echo "bad luck from Italy"
	fi
	n=$(( n + 1 ))
done
